# Creating Numpy Arrays

In [2]:
import numpy as np

In [5]:
# np.array
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
# 2D 
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
# 3D
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
# dtype   -> by default the datatype of the array is integer but using dtype we can change it to any other data type like float etc.
d = np.array([12,3,4,445,6], dtype = float)
print(d)

e = np.array([0,3,4,0,6], dtype = bool)
print(e)

f = np.array([1,2,3,4], dtype = complex)
print(f)


[ 12.   3.   4. 445.   6.]
[False  True  True False  True]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [72]:
# np.arange
a = np.arange(1,11)
print(a)

b = np.arange(1,11,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [29]:
# with reshape  ---> using this we can define the row size and column size
c = np.arange(1,13).reshape(4,3)
print(c)
print()

d = np.arange(1,13).reshape(3,4)
print(d)
print()

e = np.arange(1,13).reshape(2,6)
print(e)
print()

f = np.arange(1,13).reshape(6,2)
print(f)
print()

g = np.arange(1,17).reshape(2,2,2,2)
print(g)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [22]:
# np.ones and np.zeros
a = np.ones((3,4))
print(a)
print()
b = np.zeros((3,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
# np.random
c = np.random.random((3,4))
print(c)

[[0.52219462 0.11015661 0.66239881 0.70456429]
 [0.00743497 0.10555935 0.79160409 0.45316885]
 [0.37921381 0.4546634  0.49553551 0.13482876]]


In [26]:
# np.linspace   --> it gerenates linearly separable point between a given range
d = np.linspace(10,100,10)
print(d)
#np.linspace(10,100,10)  here 10 is the lower range 100 is the upper range and 10 is the no. of items we want between lower and upper range
# this function gerenates the number equally distanced between them
e = np.linspace(1,17,7)
print(e)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 1.          3.66666667  6.33333333  9.         11.66666667 14.33333333
 17.        ]


In [28]:
# np.identity
d = np.identity(3)
print(d)
print()
e = np.identity(4,dtype = int)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# Array Attributes

In [32]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [34]:
#ndim  ---> it tells the dimension of the array 
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [37]:
# shape  ---> it tells about the shape of the array in the form of ( no_of_row , no_of_column)
print(a1.shape)
print(a2.shape)
print(a3.shape,'there are 2 2D array of shape (2,2)')

(10,)
(3, 4)
(2, 2, 2) there are 2 2D array of shape (2,2)


In [38]:
# size   ---> tells about the no of elements in the array
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [39]:
# itemsize  ---> tells about the size of the items that it is occupying in the memory i.e, int , float etc etc..
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [41]:
# dtype    ---> tells about the data type of the items in the array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing Datatypes

In [47]:
# astype

print(a2)
print()
print(a2.dtype)
print()
a2.astype(np.float32)





[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

float64



array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

# Array Operations

In [54]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print()
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [52]:
# SCALAR OPERATIONS
# arithmetic

print(a1*2)
print()

print(a1-2)
print()

print(a1+2)
print()

print(a1/2)
print()

print(a1**2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [59]:
# relational
print(a2)
print()
print(a2 < 20)
print()
print(a2 == 18)


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]]

[[False False False False]
 [False False  True False]
 [False False False False]]


In [60]:
# VECTOR OPERATIONS  (shape of the two arrays should be same)
# arithmetic

print(a1*a2)
print()

print(a1-a2)
print()

print(a1+a2)
print()

print(a1/a2)
print()

print(a1**a2)


[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]

[[          0           1       16384    14348907]
 [          0 -1564725563  1159987200   442181591]
 [          0  1914644777 -1304428544  -122979837]]


# Array Functions

In [4]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1


array([[24.,  8., 25.],
       [69.,  2.,  3.],
       [41., 59., 59.]])

### min/max/sum/prod
- If we want to perform operation row wise or colum wise then we should use axis = 1 or axis = 0
- for row , axis = 1
- for column , axis = 0

In [5]:
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

69.0
2.0
290.0
283615171200.0


In [6]:
print(np.max(a1 , axis = 1))      # gives the max value from each row
print(np.max(a1 , axis = 0))      # gives the min value from each column


[25. 69. 59.]
[69. 59. 59.]


### mean/median/std/var
- here also we can perform operation row or column wise

In [10]:
print(np.mean(a1))
print(np.median(a1))
print(np.var(a1))
print(np.std(a1))

56.77777777777778
74.0
1351.7283950617284
36.765859095929315


### Trigonometry Functions

In [11]:
print(np.sin(a1))

[[-0.77946607  0.98935825 -0.98514626]
 [-0.30481062 -0.77946607  0.89399666]
 [-0.99999021  0.96836446  0.84147098]]


## Dot Product

In [16]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(4,3)

print(a)
print()
print(b)
print()
print('Dot Product of a and b : ')
print()
print(np.dot(a,b))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

Dot Product of a and b : 

[[114 120 126]
 [378 400 422]
 [642 680 718]]


### Log and Exponents

In [17]:
print(np.log(a1))

[[4.52178858 2.07944154 4.30406509]
 [4.09434456 4.52178858 4.49980967]
 [2.39789527 4.41884061 0.        ]]


In [18]:
print(np.exp(a1))

[[9.01762841e+39 2.98095799e+03 1.37338298e+32]
 [1.14200739e+26 9.01762841e+39 1.22040329e+39]
 [5.98741417e+04 1.11286375e+36 2.71828183e+00]]


### round / floor / ceil

In [3]:
import numpy as np
c = np.random.random((3,3))*100
print(c)
print()
print(np.round(c))
print()
print(np.floor(c))
print()
print(np.ceil(c))

[[89.3457684   9.55115285 79.69116235]
 [64.89228331 71.85774266 76.7820056 ]
 [53.80508717 31.37028328 39.10975504]]

[[89. 10. 80.]
 [65. 72. 77.]
 [54. 31. 39.]]

[[89.  9. 79.]
 [64. 71. 76.]
 [53. 31. 39.]]

[[90. 10. 80.]
 [65. 72. 77.]
 [54. 32. 40.]]


# Indexing and Slicing

In [74]:
a = np.arange(10)
b = np.arange(12).reshape(3,4)
c = np.arange(8).reshape(2,2,2)

In [43]:
print(a)
print()
print(a[0])
print(a[9])
print(a[-1])
print(a[-4])
print('*'*30,"Slicing",'*'*30)
print(a[0:5])
print(a[0:8:2])

[0 1 2 3 4 5 6 7 8 9]

0
9
9
6
****************************** Slicing ******************************
[0 1 2 3 4]
[0 2 4 6]


In [63]:
print(b)
print()
print(b[1][2])   # we can write like this also ----> b[1,2]
print(b[2,3])
print('*'*30,"2D Slicing",'*'*30)
print(b[0,:])
print()
print(b[:,1])
print()
print(b[1:,1:3])
print()
print(b[::2,::3])
print()
print(b[::2,1::2])
print()
print(b[1,::3])
print()
print(b[::2,::3])
print()
print(b[-3:-1,1:])
print()
print(b[0:2,1:])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

6
11
****************************** 2D Slicing ******************************
[0 1 2 3]

[1 5 9]

[[ 5  6]
 [ 9 10]]

[[ 0  3]
 [ 8 11]]

[[ 1  3]
 [ 9 11]]

[4 7]

[[ 0  3]
 [ 8 11]]

[[1 2 3]
 [5 6 7]]

[[1 2 3]
 [5 6 7]]


In [40]:
print(c)
print()
print(c[1,0,1])
print(c[0,0,0])
print(c[1,1,0])




[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

5
0
6


In [85]:
c1 = np.arange(27).reshape(3,3,3)
c1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [71]:
print(c1[1])
print()
print('*'*70)
print()
print(c1[::2])
print()
print('*'*70)
print()
print(c1[0][1,:])   # or we cam write c1[0,1,:] 
print()
print('*'*70)
print()
print(c1[1,:,1])
print()
print('*'*70)
print()
print(c1[2,1:,1:])
print()
print('*'*70)
print()
print(c1[::2,0,::2])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

**********************************************************************

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

**********************************************************************

[3 4 5]

**********************************************************************

[10 13 16]

**********************************************************************

[[22 23]
 [25 26]]

**********************************************************************

[[ 0  2]
 [18 20]]


# Iterating

In [77]:
print(a)
print('*'*100)
print(b)
print('*'*100)
print(c)

[0 1 2 3 4 5 6 7 8 9]
****************************************************************************************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
****************************************************************************************************
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [82]:
# 1D
print(a)
print('*'*100)

for i in a:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
****************************************************************************************************
0
1
2
3
4
5
6
7
8
9


In [83]:
# 2d
print(b)
print('*'*100)

for i in b:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
****************************************************************************************************
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [86]:
# 3D
print(c1)
print('*'*100)
for i in c1: 
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
****************************************************************************************************
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [89]:
# looping on the individual element in the 3D array
for i in np.nditer(c1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping
- reshape
- transpose
- ravel

In [93]:
# Transpose

print(b)
print()
print(np.transpose(b))
print()
print(b.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [96]:
#Ravel  --> kitne bhi dimension ke array ko 1D array mai change kar deta hain ye

print(c1)
print()
print(c1.ravel())




[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


# Stacking
- shape should be same

In [104]:
# horizontal stacking

x = np.arange(12).reshape(3,4)
y = np.arange(12,24).reshape(3,4)
print(x)
print('*'*100)
print(y)
print('*'*100)
print(np.hstack((x,y)))
print('*'*100)
print(np.hstack((x,y,x,y)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
****************************************************************************************************
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
****************************************************************************************************
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
****************************************************************************************************
[[ 0  1  2  3 12 13 14 15  0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19  4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23  8  9 10 11 20 21 22 23]]


In [103]:
# vertical stacking
print(np.vstack((x,y)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# Splitting

In [105]:
# horizontal splitting
print(np.hsplit(x,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [106]:
# vertical splitting
print(np.vsplit(x,3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
