### np.sort

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
print(a)
print()
x = np.sort(a)
print(x)
print()
xd = np.sort(a)[::-1]      # descending order
print(xd)
print()

b = np.random.randint(1,100,24).reshape(4,6)
print(b)
print()
y = np.sort(b)   # sorting wil be done row wise
print(y)
print()
z = np.sort(b,axis = 0)     # sorting will be done column wise
print(z)


[96 10 12 73 22 10 10  8 95 43  6 13 84 58  2]

[ 2  6  8 10 10 10 12 13 22 43 58 73 84 95 96]

[96 95 84 73 58 43 22 13 12 10 10 10  8  6  2]

[[73  6  1 70 13 12]
 [23 24  8 66 17 81]
 [72 93 75 56 11  1]
 [70 30 88  2 80 51]]

[[ 1  6 12 13 70 73]
 [ 8 17 23 24 66 81]
 [ 1 11 56 72 75 93]
 [ 2 30 51 70 80 88]]

[[23  6  1  2 11  1]
 [70 24  8 56 13 12]
 [72 30 75 66 17 51]
 [73 93 88 70 80 81]]


### np.append
The numpy.append() appends values along the mentioned axis at the end of the array

In [14]:
a = np.random.randint(1,100,10)
b = np.random.randint(1,100,20).reshape(5,4)
print(a)
a1 = np.append(a,200)
print(a1)
print()
print(b)
print()
b1 = np.append(b,np.ones((b.shape[0],1)),axis=1)
print(b1)


[23 60 85 44 44 77 55 47 45 73]
[ 23  60  85  44  44  77  55  47  45  73 200]

[[20 74 69 99]
 [56 66 87 41]
 [21 49 82 99]
 [11 90 14  1]
 [16 11 62 90]]

[[20. 74. 69. 99.  1.]
 [56. 66. 87. 41.  1.]
 [21. 49. 82. 99.  1.]
 [11. 90. 14.  1.  1.]
 [16. 11. 62. 90.  1.]]


### np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [16]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
e = np.concatenate((c,d),axis=0)  # row wise
f = np.concatenate((c,d),axis=1)  # column wise
print(c)
print()
print(d)
print()
print(e)
print()
print(f)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


### np.unique
With the help of np.unique() method, we get the unique values from an array given as parameter in np.unique() method

In [17]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print()
print(f)
print()
eu = np.unique(e)
fu = np.unique(f)
print(eu)
print()
print(fu)

[1 1 2 2 3 3 4 4 5 5 6 6]

[[1 2 3 1]
 [1 2 3 2]]

[1 2 3 4 5 6]

[1 2 3]


### np.expand_dims
With the help of this, we can get the expanded dimensions of the array

In [18]:
a = np.random.randint(1,100,10)
print(a)
print(a.shape)
print()
print(np.expand_dims(a,axis=0))
print(np.expand_dims(a,axis=0).shape)
print()
print(np.expand_dims(a,axis=1))
print(np.expand_dims(a,axis=1).shape)

[94 14 99 78  2 12 90 58 79 96]
(10,)

[[94 14 99 78  2 12 90 58 79 96]]
(1, 10)

[[94]
 [14]
 [99]
 [78]
 [ 2]
 [12]
 [90]
 [58]
 [79]
 [96]]
(10, 1)


### np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [22]:
a = np.random.randint(1,100,10)
print(a)
print(np.where(a>50))

[ 3 24 54 37 94 58 76 97 93 99]
(array([2, 4, 5, 6, 7, 8, 9], dtype=int64),)


In [23]:
# replace all values >50 with 0       syntax--> np.where(condition,true,false)
print(np.where(a>50,0,a))


[ 3 24  0 37  0  0  0  0  0  0]


In [24]:
# replace even elements with 0
print(np.where(a%2==0,0,a))

[ 3  0  0 37  0  0  0 97 93 99]


### np.argmax / np.argmin
- The numpy.argmax() function returns indices of the max element of the array in a particular axis.
- The numpy.argmin() function returns indices of the min element of the array in a particular axis.

In [27]:
# np.argmax
a = np.random.randint(1,100,10)
b = np.random.randint(1,100,20).reshape(5,4)
print(a)
print()
print(np.argmax(a))
print()
print(b)
print()
print(np.argmax(b,axis = 0))
print()
print(np.argmax(b,axis = 1))

[97 51 42  9 15 20 36 93 81 26]

0

[[79 82 78 86]
 [90 11 92  9]
 [49 69 49 72]
 [60 19 69 32]
 [57 22 82 72]]

[1 0 1 0]

[3 2 3 2 2]


In [26]:
# np.argmin()
a = np.random.randint(1,100,10)
b = np.random.randint(1,100,20).reshape(5,4)
print(a)
print()
print(np.argmin(a))
print()
print(b)
print()
print(np.argmin(b,axis = 0))
print()
print(np.argmin(b,axis = 1))

[ 6 29 74 10 30  7 61 21 66 71]

0

[[68 64 96  2]
 [16 39 78 91]
 [97 42 24 33]
 [13 37 76 21]
 [91 91 91 64]]

[3 3 2 0]

[3 0 2 0 3]


### np.cumsum
This function is used when we want to compute the cumulative sum of the array elements over a given axis.

In [31]:
x = np.arange(10)
y = np.arange(20).reshape(4,5)
print(x)
print()
print(np.cumsum(x))
print()

print(y)
print()
print(np.cumsum(y, axis = 1))   # row wise
print()
print(np.cumsum(y, axis = 0))   # column wise

[0 1 2 3 4 5 6 7 8 9]

[ 0  1  3  6 10 15 21 28 36 45]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 0  1  3  6 10]
 [ 5 11 18 26 35]
 [10 21 33 46 60]
 [15 31 48 66 85]]

[[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]
 [30 34 38 42 46]]


### np.cumprod

In [33]:
x = np.arange(1,11)
y = np.arange(1,21).reshape(4,5)
print(x)
print()
print(np.cumprod(x))
print()

print(y)
print()
print(np.cumprod(y, axis = 1))   # row wise
print()
print(np.cumprod(y, axis = 0))   # column wise

[ 1  2  3  4  5  6  7  8  9 10]

[      1       2       6      24     120     720    5040   40320  362880
 3628800]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[      1       2       6      24     120]
 [      6      42     336    3024   30240]
 [     11     132    1716   24024  360360]
 [     16     272    4896   93024 1860480]]

[[    1     2     3     4     5]
 [    6    14    24    36    50]
 [   66   168   312   504   750]
 [ 1056  2856  5616  9576 15000]]


### np.percentile
This function is used to compute the n th percentile of the given data (array elements) along the specified axis.

In [34]:
a = np.random.randint(1,100,10)
print(a)
print()
print(np.percentile(a,0))
print()
print(np.percentile(a,100))
print()
print(np.percentile(a,50))
print()
print(np.percentile(a,25))
print()
print(np.percentile(a,75))

[38  9  8 41 58 19 16 66  7 33]

7.0

66.0

26.0

10.75

40.25


### np.histogram
Numpy has a built in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [38]:
x = np.random.randint(1,100,20)
print(x)
print()
print(np.histogram(x,bins=[0,10,20,30,40,50,60,70,80,90,100]))
print()
print(np.histogram(x,bins=[0,50,100]))

[57 75 77 95 72 76  6 39 23 52 90 30 33 21 84 45 84 27 98 32]

(array([1, 0, 3, 4, 1, 2, 0, 4, 2, 3], dtype=int64), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

(array([ 9, 11], dtype=int64), array([  0,  50, 100]))


### np.corrcoef
Returns Pearson product moment correlation coefficients. 
- It's value range from -1 to 1.
- 1 means strongly co-related.
- -1 means negatively co-related, which means if one values increases then the other value decreases.

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

# Output format
#              salary      experience
# salary         1           0.23445
# experience    0.39874       1


###  np.isin
With the help of numpy.isin() method , we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [44]:
a = np.random.randint(1,100,10)
items = [10,20,30,40,50]
print(a)
print(np.isin(a,items))
print(a[np.isin(a,items)])



[72 50 68 83 85 80 96 24 77 60]
[False  True False False False False False False False False]
[50]


### np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [45]:
print(a)
print(np.flip(a))

[72 50 68 83 85 80 96 24 77 60]
[60 77 24 96 80 85 83 68 50 72]


In [48]:
b = np.arange(20).reshape(4,5)
print(b)
print()
print(np.flip(b))
print()
print(np.flip(b,axis = 0))
print()
print(np.flip(b,axis = 1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]

[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


### np.put
The numpy.put() function returns specific elements of an array with given values of p_array. Array indexed works on flattened array.


In [49]:
a = np.arange(10)
print(a)
np.put(a,[0,1,2],[100,200,300])
print(a)

[0 1 2 3 4 5 6 7 8 9]
[100 200 300   3   4   5   6   7   8   9]


### np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrys along with the mentioned axis.

In [53]:
print(a)
a1 = np.delete(a,[2,5,8])
print(a1)
print(a)


[100 200 300   3   4   5   6   7   8   9]
[100 200   3   4   6   7   9]
[100 200 300   3   4   5   6   7   8   9]


### Set Functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [58]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

print(np.union1d(m,n))
print(np.intersect1d(m,n))
print(np.setdiff1d(m,n))
print(np.setxor1d(m,n))
print(np.in1d(m,4))
print(m[np.in1d(m,4)])

[1 2 3 4 5 6 7]
[3 4 5]
[1 2]
[1 2 6 7]
[False False False  True False]
[4]


### np.clip
numpy.clip() function is used to clip (limit) the values in an array.

In [62]:
a = np.random.randint(1,1000,10)
print(a)
print()
np.clip(a,a_min = 200,a_max = 700)

[746  32 123 113 145 594 713 406 703 324]



array([700, 200, 200, 200, 200, 594, 700, 406, 700, 324])